//base
const ELEMENT_NODE = 1;
const SLIDER_ANIMATION_CLASS = 'slider-animation';

const LEFT_KEYCODE = 37;
const RIGHT_KEYCODE = 39;


export {
  ELEMENT_NODE,
  SLIDER_ANIMATION_CLASS,
  LEFT_KEYCODE,
  RIGHT_KEYCODE,
}